Repository evidence-dev/evidence, pull requests merged in 2024-02, with the labels that each got.

#1486 Move context.js -> component utilities chartContext.js
  .changeset/brown-rings-shave.md
  packages/component-utilities/src/chartContext.js
  packages/core-components/src/lib/unsorted/viz/area/Area.svelte
  packages/core-components/src/lib/unsorted/viz/bar/Bar.svelte
  packages/core-components/src/lib/unsorted/viz/box/Box.svelte
  packages/core-components/src/lib/unsorted/viz/bubble/Bubble.svelte
  packages/core-components/src/lib/unsorted/viz/context.js
  packages/core-components/src/lib/unsorted/viz/core/_BigValue.svelte
  packages/core-components/src/lib/unsorted/viz/core/_Chart.svelte
  packages/core-components/src/lib/unsorted/viz/core/_Value.svelte
  packages/core-components/src/lib/unsorted/viz/funnel/_FunnelChart.svelte
  packages/core-components/src/lib/unsorted/viz/histogram/Hist.svelte
  packages/core-components/src/lib/unsorted/viz/line/Line.svelte
  packages/core-components/src/lib/unsorted/viz/map/_USMap.svelte
  packages/core-components/src/lib/unsorted/viz/references/ReferenceArea.svelte
  packages/core-components/src/lib/unsorted/viz/references/ReferenceLine.svelte
  packages/core-components/src/lib/unsorted/viz/sankey/SankeyDiagram.svelte
  packages/core-components/src/lib/unsorted/viz/scatter/Scatter.svelte
  packages/core-components/src/lib/unsorted/viz/table/Column.svelte
  packages/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
Labels: ready-to-merge

#1529 Update type information to be more in line with USQL
  .changeset/wild-trains-drive.md
  packages/component-utilities/src/getColumnEvidenceType.js
  packages/component-utilities/src/getColumnSummary.js
  packages/component-utilities/src/inferColumnTypes.js
  packages/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
  sites/test-env/pages/wack-dates.md
Labels: ready-to-merge

#1555 chore: update mysql
  .changeset/new-numbers-listen.md
  packages/mysql/package.json
  pnpm-lock.yaml
Labels: ready-to-merge

#1492 Plugin Authoring Docs
  sites/docs/docs/plugins/component-plugins.md
  sites/docs/docs/plugins/creating-a-plugin/components.md
  sites/docs/docs/plugins/creating-a-plugin/datasources.md
  sites/docs/docs/plugins/creating-a-plugin/index.md
  sites/docs/docs/plugins/source-plugins.md
Labels: documentation, ready-to-merge

#1517 Basic Theme Support
  .changeset/fluffy-snakes-type.md
  .changeset/sour-rice-applaud.md
  packages/core-components/src/lib/unsorted/ui/Sidebar.svelte
  pnpm-lock.yaml
  sites/example-project/tailwind.config.cjs
  sites/test-env/pages/index.md
  sites/test-env/pages/theme.md
  sites/test-env/tailwind.config.cjs
Labels: do not merge

#1639 Add Sparkline component and replace tiny-linked-charts dependency
  .changeset/purple-bees-mate.md
  package.json
  packages/core-components/package.json
  packages/core-components/src/lib/unsorted/ui/LineBreak.svelte
  packages/core-components/src/lib/unsorted/viz/core/Sparkline.svelte
  packages/core-components/src/lib/unsorted/viz/core/_BigValue.svelte
  packages/core-components/src/lib/unsorted/viz/core/_Sparkline.svelte
  packages/core-components/src/lib/unsorted/viz/core/sparkline.js
  packages/core-components/src/lib/unsorted/viz/index.js
  packages/evidence/package.json
  packages/evidence/scripts/build-template.js
  pnpm-lock.yaml
  sites/docs/docs/components/big-value.md
  sites/docs/docs/components/print-format-components.md
  sites/docs/docs/components/sparkline.md
  sites/docs/static/img/sparkline-basic.png
  sites/docs/static/img/sparkline-connected.gif
  sites/example-project/package.json
  sites/example-project/src/pages/text-and-metrics/big-value/+page.md
  sites/example-project/src/pages/text-and-metrics/sparkline/+page.md
  sites/example-project/vite.config.js
Labels: to-review

#1646 support for algolia docsearch
  packages/core-components/package.json
  packages/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
  packages/core-components/src/lib/organisms/layout/header/AlgoliaDocSearch.svelte
  packages/core-components/src/lib/organisms/layout/header/Header.svelte
  packages/core-components/src/lib/organisms/layout/header/SearchButton.css
  pnpm-lock.yaml
Labels: to-review
